# Generated by Django 4.2.5 on 2024-06-27 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
