# Generated by Django 4.2.5 on 2024-06-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
