# Generated by Django 4.2.5 on 2024-06-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0007_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cvv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='number_of_card',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
