# Generated by Django 4.2.5 on 2024-07-08 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0009_order_first_name_order_last_name_order_middle_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='order',
            name='month',
        ),
        migrations.RemoveField(
            model_name='order',
            name='number_of_card',
        ),
        migrations.RemoveField(
            model_name='order',
            name='year',
        ),
    ]
