# Generated by Django 4.2.5 on 2024-06-13 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_product', '0003_remove_filter_products_product_filters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavour',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='flavour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog_product.flavour'),
        ),
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=models.ManyToManyField(to='catalog_product.filter'),
        ),
    ]
