# Generated by Django 4.2.5 on 2024-06-13 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_product', '0005_remove_product_flavour_product_flavour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='flavour',
        ),
        migrations.AddField(
            model_name='flavour',
            name='for_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog_product.product'),
        ),
        migrations.AddField(
            model_name='flavour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
