# Generated by Django 4.2.5 on 2024-06-29 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_product', '0008_productincart_flavour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productincart',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='productincart',
            name='flavour',
        ),
        migrations.RemoveField(
            model_name='productincart',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='ProductInCart',
        ),
    ]
