# Generated by Django 4.2.5 on 2024-06-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_product', '0009_remove_productincart_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_of_product',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
