# Generated by Django 4.2.5 on 2024-06-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_product', '0010_product_count_of_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='count_of_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='flavour',
            name='count_of_product',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
